theme: jekyll-theme-architect

title: [jacc-spec]
description: [Maintenance Project for the JACC Specification, JSR-15]

# sidebar links url
links:
  source: https://github.com/javaee/jacc-spec
  #download:
  #mailinglist:
  #javadocs:
  #docs:
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

